### ISSUE TITLE
Can we make it case sensitive?

### ISSUE THREAD

**Issue by arunvarghe** [kumbhar-ketan/react-canvas-captcha#1]
Can we make it case-sensitive? It is not case sensitive. It is always small letter . Can we get code as it is shown in the image with capital and small letter?

**Comment by kumbhar-ketan** [comment]
Hi @arunvarghe,
Thanks for your suggestion. we have added caseType property to make it case sensitive & non case sensitive based on caseType value.
From the version 1.0.14, it will be by default the combination of lowercase & uppercase characters to generate captcha.
In case if you want lower case characters only then you can pass caseType="lowercase", if you want upper case characters only then you can pass "uppercase".

I hope this will help you. Thanks.
